name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup Node
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '20.11.1'
      - name: Install Dependencies
        run: npm ci
      - name: Save error log
        uses: actions/upload-artifact@v4.4.3
        if: ${{ failure() }}
        with:
          name: npm-debug-log-${{ hashFiles('package-lock.json') }}
          path: npm-debug.log
      - name: Test
        run: npm test
      - name: Report Coverage
        uses: codecov/codecov-action@v4.6.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Lint
        run: npm run lint
      - name: Pack
        run: npm pack
